package auction.optimisation.stage1;
public class OptimisedBidder {

	public static void main(String[] args) {

	double budget = 200;
	
	ScenarioGenerator scenGen = new ScenarioGenerator();		//Create an instance of the ScenarioGenerator class
	scenGen.createItemAndAuction();
	
	for (int i=0; i<scenGen.Auctions.size(); i++){		//Iterate through the ArrayList of auctions generated by the scenario generator
		Auction auction = scenGen.Auctions.get(i);
		System.out.println(auction.item.title+" has a sure bid of $"+auction.sureBid+" and an rrp of $"+auction.item.rrp+" giving it a buyer utility of £"+auction.utility);
	}
	
	System.out.println("\n");
	
	Optimiser optimiser = new Optimiser();					//Instantiate the optimiser class
	optimiser.optimiseAllocation(scenGen.Auctions, budget);	// Send the list of auctions and the budget to the optimiseAllocation method
	}

}
